import os

CHANGE_LIGHTS_FREQ = 15
GET_DATA_FREQ = 1
SEND_REPORT_FREQ = 1
RECEIVE_REPORT_FREQ = 1
PRINT_REPORT_FREQ = 1
UPDATE_TOPOLOGY_FREQ = 1

ROOT_DIR_PATH = os.path.dirname(os.path.abspath(__file__))