import os

CHANGE_LIGHTS_FREQ = 15
GET_DATA_FREQ = 1
REPORT_TO_MANAGER_FREQ = 10
RECEIVE_REPORT_FREQ = 1
REPORT_SITUATION_FREQ = 5
UPDATE_TOPOLOGY_FREQ = 1

ROOT_DIR_PATH = os.path.dirname(os.path.abspath(__file__))